name: ssl-v1
channels:
  - pytorch-nightly
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argcomplete=3.3.0=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310hd8f1fbe_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2025.1.31=py310h06a4308_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cuda-version=11.3=hbc958af_3
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cupy=12.2.0=py310hf4db66c_4
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - docstring_parser=0.16=pyhd8ed1ab_0
  - einops=0.7.0=pyhd8ed1ab_1
  - expat=2.5.0=h6a678d5_0
  - faiss-gpu=1.8.0=py3.10_h4c7d538_0_cuda12.1.1
  - fastrlock=0.8.2=py310hc6cd4ac_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - gcc=9.5.0=h1fea6ba_13
  - gcc_impl_linux-64=9.5.0=h6c5bc03_17
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx=9.5.0=h1fea6ba_13
  - gxx_impl_linux-64=9.5.0=h6c5bc03_17
  - icu=73.1=h6a678d5_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.0=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jsonargparse=4.28.0=pyhd8ed1ab_0
  - jsonnet=0.17.0=py310hd8f1fbe_3
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libfaiss=1.8.0=h046e95b_0_cuda12.1.1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=9.5.0=h367e8d2_17
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsanitizer=9.5.0=hf86b28c_17
  - libstdcxx-devel_linux-64=9.5.0=h367e8d2_17
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - lightning-flash=0.8.2=pyhd8ed1ab_0
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.8.4=py310h06a4308_0
  - matplotlib-base=3.8.4=py310h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.1=hb9d3cd8_3
  - packaging=24.0=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - ply=3.11=py310h06a4308_0
  - protobuf=3.20.3=py310h6a678d5_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pynndescent=0.5.12=pyhca7485f_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-lightning=1.9.4=pyhd8ed1ab_1
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - referencing=0.34.0=pyhd8ed1ab_0
  - rpds-py=0.18.0=py310hcb5633a_0
  - scikit-learn=1.4.2=py310h1fdf081_0
  - scipy=1.13.0=py310hb13e2d6_0
  - setuptools=68.2.2=py310h06a4308_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - sysroot_linux-64=2.17=h0157908_18
  - threadpoolctl=3.4.0=pyhc1e730c_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - torchmetrics=0.10.3=pyhd8ed1ab_0
  - tornado=6.3.3=py310h5eee18b_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - validators=0.28.0=pyhd8ed1ab_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - albucore==0.0.13
      - albumentations==1.4.14
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - beartype==0.18.5
      - beautifulsoup4==4.13.4
      - cachetools==6.2.0
      - cloudpickle==3.0.0
      - colt5-attention==0.10.20
      - cuda-bindings==12.9.2
      - cuda-pathfinder==1.3.0
      - cuda-python==12.9.2
      - cudf-cu12==25.8.0
      - cuml-cu12==25.8.0
      - cupy-cuda12x==13.6.0
      - cuvs-cu12==25.8.0
      - cython==0.29.37
      - dask==2025.7.0
      - dask-cuda==25.8.0
      - dask-cudf-cu12==25.8.0
      - datasets==2.21.0
      - deepspeed==0.16.4
      - dill==0.3.8
      - diskcache==5.6.3
      - distributed==2025.7.0
      - distributed-ucxx-cu12==0.45.1
      - eval-type-backport==0.2.0
      - filelock==3.17.0
      - frozenlist==1.4.1
      - fsspec==2025.2.0
      - gdown==5.2.0
      - girder-client==3.2.11
      - gputil==1.4.0
      - h5py==3.13.0
      - hdbscan==0.8.33
      - hjson==3.1.0
      - huggingface-hub==0.24.6
      - imageio==2.34.2
      - importlib-metadata==8.7.0
      - jinja2==3.1.5
      - kagglehub==0.3.13
      - lazy-loader==0.4
      - libcudf-cu12==25.8.0
      - libcuml-cu12==25.8.0
      - libcuvs-cu12==25.8.0
      - libkvikio-cu12==25.8.0
      - libraft-cu12==25.8.0
      - librmm-cu12==25.8.0
      - libucx-cu12==1.18.1
      - libucxx-cu12==0.45.1
      - lightning==2.5.0.post0
      - llvmlite==0.44.0
      - local-attention==1.9.1
      - locket==1.0.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - msgpack==1.1.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numba==0.61.2
      - numba-cuda==0.14.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cccl-cu12==12.9.27
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvtx==0.2.13
      - oapackage==2.7.13
      - opencv-python==4.10.0.82
      - opencv-python-headless==4.10.0.84
      - openslide-bin==4.0.0.8
      - openslide-python==1.1.2
      - pandas==2.3.2
      - partd==1.4.2
      - pillow==11.1.0
      - pip==25.2
      - plotly==5.22.0
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.19.2
      - pylibcudf-cu12==25.8.0
      - pylibraft-cu12==25.8.0
      - pynvjitlink-cu12==0.7.0
      - pynvml==12.0.0
      - raft-dask-cu12==25.8.0
      - rapids-dask-dependency==25.8.0
      - rapids-logger==0.1.1
      - regex==2024.7.24
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rmm-cu12==25.8.0
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - seaborn==0.13.2
      - shapely==2.0.4
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - submitit==1.5.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tbb==2021.12.0
      - tblib==3.1.0
      - tenacity==8.3.0
      - tifffile==2024.7.2
      - timm==0.9.16
      - tokenizers==0.19.1
      - toolz==1.0.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchstain==1.3.0
      - torchvision==0.21.0
      - tqdm==4.66.5
      - transformers==4.44.2
      - treelite==4.4.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - ucx-py-cu12==0.45.0
      - ucxx-cu12==0.45.1
      - umap-learn==0.5.4
      - xformers==0.0.29.post3
      - xxhash==3.5.0
      - yarl==1.9.4
      - zict==3.0.0
      - zipp==3.23.0
